services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres_initialized:12
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - TZ=Europe/Moscow
    ports:
      - 2345:5432