spring:
  # JDBC
  datasource:
    url: jdbc:postgresql://localhost:5432/walletservice
    username: postgres
    password: "999111"
    driver-class-name: org.postgresql.Driver
  # Liquibase
  liquibase:
    change-log: db/changelog/changelog.xml
    default-schema: walletservice
    liquibase-schema: liquibase