# Common
common:
  url: jdbc:postgresql://localhost:5432/walletservice
  username: postgres
  password: "999111"

# JDBC
jdbc:
  driver: org.postgresql.Driver

# Liquibase
liquibase:
  changeLogFile: db/changelog/changelog.xml
  defaultSchemaName: walletservice
  liquibaseSchemaName: liquibase